version: "3.8"
services:
  tasks:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

  mongo-frontend:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
    links:
      - mongo